### ISSUE TITLE
need khl-voice function

### ISSUE THREAD

**Issue by A1LExX** [Quatrecentquatre-404/kaiheila.js#2]
fi6 provide a package that name is khl-voice  link: [npmjs](https://www.npmjs.com/package/khl-voice)

**Comment by Quatrecentquatre-404** [comment]
Thanks for the issue, I was not aware that Kaiheila supports the voice for Bots. I'll update this as soon as possible.

**Comment by Quatrecentquatre-404** [comment]
Actually, I don't think I'm gonna put this in the project since it's not opensource. The binaries seems to be compiled from fi6 but their code is not readable, though it requires the Kaiheila bot's token.
